server:
    port: 8088

spring:
    profiles:
        active: core

    kafka:
        bootstrap-servers: host.docker.internal:9092
        consumer:
            group-id: notification
            enable-auto-commit: true
            auto-offset-reset: latest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: com.myproject.kafka.serializers.CustomDeserializer
            
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: com.myproject.kafka.serializers.CustomSerializer


externalClient:
    uri: "http://host.docker.internal:8087/api/v1"
    naverSms:
        from: ${naverSmsFrom}