server:
    port: 8088


spring:
    kafka:
        consumer:
            bootstrap-servers: localhost:9092
            group-id: alarm
            # auto-offset-reset:
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kakfa.common.serialization.StringDeserializer
        producer:
            bootstrap-servers: localhost:9092
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kakfa.common.serialization.StringDeserializer
            