server:
    port: 8088

spring:
    kafka:
        consumer:
            bootstrap-servers: localhost:9092
            group-id: alarm
            # auto-offset-reset:
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kakfa.common.serialization.StringDeserializer
        producer:
            bootstrap-servers: localhost:9092
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kakfa.common.serialization.StringDeserializer
            

externalClient:
    url: "http://127.0.0.1:8087/api/v1"