FROM order-app

WORKDIR /order-app/auth

# RUN chmod +x ./gradlew
# RUN ./gradlew build

ARG JAR_FILE=/build/libs/*.jar
COPY ${JAR_FILE} /build/libs/auth.jar

ENTRYPOINT [ "java", "-jar", "/build/libs/auth.jar"]
# -e