
server:
    port: 8087

naverSms:
    uri: "https://sens.apigw.ntruss.com/sms/v2/services"
    serviceId: "ncp:sms:kr:258392559149:order-messaging"
    accessKey: oBdD4C4WfQgVUm1FGvMM
    secretKey: ${naverSmsKey}
    from: ${naverSmsFrom}

logging:
  level: 
    root: DEBUG


