
server:
    port: 8087

naverSms:
    domain: "https://sens.apigw.ntruss.com"
    path: "/sms/v2/services/ncp:sms:kr:258392559149:order-messaging"
    serviceId: "ncp:sms:kr:258392559149:order-messaging"
    accessKey: ugkC6gSAKALomjMNlWFs
    secretKey: ${naverSmsKey}
    from: ${naverSmsFrom}

kakao:
  restApiKey: ""

  maps:
    domain: "https://dapi.kakao.com"

  mobility:
    domain: "https://apis-navi.kakaomobility.com"
    



logging:
  level: 
    root: DEBUG

feign:
  client:
    config:
      default:
        loggerLevel: FULL


