FROM order-app

WORKDIR /order-app/external-client

# RUN chmod +x ./gradlew
# RUN ./gradlew build

ARG JAR_FILE=/build/libs/*.jar
COPY ${JAR_FILE} external-client.jar

ENTRYPOINT [ "java", "-jar", "external-client.jar"]
# -e