FROM order-app

WORKDIR /order-app/order-api

# RUN chmod +x ./gradlew
# RUN ./gradlew build

ARG JAR_FILE=/build/libs/*.jar
COPY ${JAR_FILE} order-api.jar

ENTRYPOINT [ "java", "-jar", "order-api.jar"]
# -e