spring:
    datasource:
        url: jdbc:mysql://mysql:3306/commercedb?useSSL=false&allowPublicKeyRetrieval=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: pfuser1234 #${dbPassword}
    
    jpa:
        hibernate:
            ddl-auto: create
            

logging:
    level:
        root: DEBUG
        org:
            hibernate:
                type: TRACE
                sql: DEBUG

header:
    secretKey: gpejrhdxhddlswmdzl123!@#