spring:
    datasource:
        url: "jdbc:mysql://127.0.0.1:3306/commercedb" # host.docker.internal
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: pfuser
        password: ${dbPassword}
    
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none
            

logging:
    level:
        root: DEBUG
        org:
            hibernate:
                type: TRACE
                sql: DEBUG

header:
    secretKey: gpejrhdxhddlswmdzl123!@#