spring:
    datasource:
        url: jdbc:mysql://./localhost:3306/commercedb
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: pfuser
        password: ${dbPassword}

secretKey: ${secretKey} # with -e